{"name": "  + 2", "status": "passed", "description": "\n        单元测试加法运算，预期异常\n        :param add_fail_data:加法的参数化异常数据\n        :param setup_class: 实例化计算器代码\n        :return: 断言结果\n        ", "steps": [{"name": "执行计算   + 2", "status": "passed", "start": 1624373024500, "stop": 1624373024500}], "attachments": [{"name": "log", "source": "b110e7ce-52e2-4046-823f-79d514256612-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "add_fail_data", "value": "[' ', 2, 'Exception']"}], "start": 1624373024500, "stop": 1624373024500, "uuid": "2025f2cf-88a5-4286-8aaf-f59319e14680", "historyId": "ba91372995ec1a45626df1761e974341", "testCaseId": "4f753dce75c8ee3a58b252822cddc783", "fullName": "testing.test_calculator.TestCalculator#test_add_exception", "labels": [{"name": "feature", "value": "计算器测试用例"}, {"name": "story", "value": "异常数据的加法"}, {"name": "parentSuite", "value": "testing"}, {"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "MS-DPHROIDQRVFN"}, {"name": "thread", "value": "10556-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testing.test_calculator"}]}